# Generated by Django 6.1.1 on 2026-09-20 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('enrollment', models.CharField(max_length=16, unique=True)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('IT', 'Information Technology'), ('CE', 'Civil Engineering'), ('ME', 'Mechanical Engineering'), ('EC', 'Electronics & Communication')], max_length=3)),
                ('passout_year', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)])),
            ],
        ),
    ]
