# Generated by Django 6.1.1 on 2026-09-22 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='accesModules',
            new_name='accessModules',
        ),
    ]
